[project]
name = "neviweb130"
description = "Home assistant custom_components to manage Sinopé ZigBee and Wi-Fi devices."
version = "2.0"
dynamic = ["version"]
urls = { repository = "https://github.com/claudegel/sinope-130" }
authors = [{ name = "Claude Gélinas", email = "claude@phyto.qc.ca" }]
readme = "README.md"
license = { text = "Apache-2.0" }
requires-python = ">=3.13"

[tool.poetry]
packages = [ { include = "custom_components" } ]

[tool.poetry.dependencies]
python = "^3.13"
homeassistant = "^2025.2.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.17.1"
homeassistant-stubs = "^2025.2.0"
types-aiofiles = "^23.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ["py313"]

[tool.isort]
profile = "black"
line_length = 120

[tool.flake8]
max-line-length = 120

[tool.mypy]
python_version = "3.13"
check_untyped_defs = true
warn_unused_ignores = true
show_error_codes = true

[tool.ruff]
line-length = 120
fix = true

[tool.pyupgrade]
py313plus = true

[tool.codespell]
skip = "Contributors.md,custom_components/neviweb130/translations/*.json"
ignore-words-list = "hass"
quiet-level = 2
