name: mypy

on:
  pull_request:
  push:
    branches: [master]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      - name: Install the project and dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run mypy
        run: uv run mypy .
